export const STORAGE_KEY = "trader-journal-v1";

export const createSeedEntries = () => [
  {
    id: crypto.randomUUID(),
    title: "NIFTY Breakout Long",
    date: "2026-05-20",
    symbol: "NIFTY",
    market: "Index",
    strategy: "Breakout + VWAP Retest",
    direction: "Long",
    status: "Closed",
    pnl: 12450,
    risk: 2,
    confidence: 8,
    mood: "Focused",
    tags: ["breakout", "discipline"],
    setup: "Morning range high broken with volume confirmation.",
    execution:
      "Entered after clean retest above VWAP. Partial exits at 1R and 2R.",
    mistakes: "Could have sized better after first pullback held.",
    lessons: "Patience at open gave higher quality entry.",
    checklist: {
      plan: true,
      stopPlaced: true,
      positionSized: true,
      journaled: true,
    },
    screenshots: "",
    favorite: true,
    pinned: true,
    updatedAt: Date.now() - 36000000,
    createdAt: Date.now() - 86400000,
  },
  {
    id: crypto.randomUUID(),
    title: "BANKNIFTY Reversal Short",
    date: "2026-05-18",
    symbol: "BANKNIFTY",
    market: "Index",
    strategy: "Failed Breakout Reversal",
    direction: "Short",
    status: "Closed",
    pnl: -3850,
    risk: 1,
    confidence: 6,
    mood: "Anxious",
    tags: ["reversal", "risk-control"],
    setup: "False breakout above day high with weak breadth.",
    execution: "Entry was early. Stop respected quickly.",
    mistakes: "Jumped in before confirmation candle close.",
    lessons: "Wait for confirmation to reduce noise trades.",
    checklist: {
      plan: true,
      stopPlaced: true,
      positionSized: true,
      journaled: true,
    },
    screenshots: "",
    favorite: false,
    pinned: false,
    updatedAt: Date.now() - 76000000,
    createdAt: Date.now() - 128000000,
  },
];

export const createEmptyEntry = () => ({
  title: "",
  date: new Date().toISOString().slice(0, 10),
  symbol: "",
  market: "Stocks",
  strategy: "",
  direction: "Long",
  status: "Planned",
  pnl: 0,
  risk: 1,
  confidence: 5,
  mood: "Calm",
  tags: [],
  setup: "",
  execution: "",
  mistakes: "",
  lessons: "",
  checklist: {
    plan: false,
    stopPlaced: false,
    positionSized: false,
    journaled: false,
  },
  screenshots: "",
  favorite: false,
  pinned: false,
});

export const moodOptions = ["Calm", "Focused", "Confident", "Anxious", "Frustrated"];
export const statusOptions = ["Planned", "Open", "Closed"];
export const marketOptions = ["Stocks", "Options", "Futures", "Forex", "Crypto", "Index"];
export const sortOptions = [
  { value: "updatedAt", label: "Recently Updated" },
  { value: "date", label: "Trade Date" },
  { value: "pnl", label: "P&L" },
  { value: "confidence", label: "Confidence" },
  { value: "risk", label: "Risk" },
];